# Enable all rules by default
default: true

# Path to config file to extend if needed
extends: null

# MD003/heading-style atx : # Heading 1
MD003:
  style: atx

# MD004/ul-style dash : - Bullet list
MD004:
  style: dash

# MD007/ul-indent 2 : - Bullet list
MD007:
  indent: 4
  start_indented: false

# MD010/no-hard-tabs : Disallow hard tabs
MD010:
  code_blocks: true # Include code blocks
  # Fenced code languages to ignore
  ignore_code_languages:
    - shell
    - bash
    - dockerfile
    - yaml
    - json
  spaces_per_tab: 4

